class ListData {
  final List<String> skills = [
    'Java',
    'Python',
    'C++',
    'Flutter',
    'JavaScript',
    'Ruby',
    'Project Management',
    'Business Analysis',
    'Machine Learning',
    'AI',
    'Data Science',
    'SQL',
    'HTML',
    'CSS',
    'React',
    'Node.js',
    'Cloud Computing',
    'DevOps',
    'Git',
    'GitHub',
    'Leadership',
    'Communication',
    'Problem-solving',
    'Time Management',
    'Negotiation Skills',
    'Customer Service',
    'Public Speaking',
    'Creative Writing',
    'Graphic Design',
    'UI/UX Design',
    'Web Design',
    'Photoshop',
    'InDesign',
    'Illustration',
    'Marketing Strategy',
    'Sales Strategy',
    'Financial Management',
    'Web Development',
    'Blockchain',
    'Cybersecurity',
    'Social Media Management',
    'Video Editing',
    'Branding',
    'Digital Marketing',
    'Database Management',
    'Negotiation',
    'Conflict Resolution',
    'Data Analysis',
    '3D Modeling',
    'Customer Relationship Management',
    'Entrepreneurship'
  ];
}
