name: track_tracing
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  curved_navigation_bar: ^1.0.6
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  flutter_swipe_button: ^2.1.3
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  lottie: ^3.1.3
  path: ^1.9.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+1
  syncfusion_flutter_charts: ^27.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/